#ifndef HAL_ARCH_EXCEPTION_H
#define HAL_ARCH_EXCEPTION_H

#ifndef __ASSEMBLER__
#include <stdbool.h>
#include <stdint.h>
#include <plane/compiler.h>

struct interrupt_frame {
	/* generated by pusha macro */
	uint64_t r15;
	uint64_t r14;
	uint64_t r13;
	uint64_t r12;
	uint64_t r11;
	uint64_t r10;
	uint64_t r9;
	uint64_t r8;
	uint64_t rbp;
	uint64_t rdi;
	uint64_t rsi;
	uint64_t rdx;
	uint64_t rcx;
	uint64_t rbx;
	uint64_t rax;

	/* interrupt route info */
	uint64_t int_no;       /* 0~255 */
	uint64_t error_code;   /* 0 if hardware does not push one */

	/* handled by hardware */
	uint64_t rip;
	uint64_t cs;
	uint64_t rflags;
	uint64_t rsp;
	uint64_t ss;
} __packed;

bool x86_64_try_handle_page_fault(uint64_t int_no,
				  uint64_t fault_addr,
				  uint64_t error_code);
void x86_64_exception_handler(struct interrupt_frame *frame);

#endif /* __ASSEMBLER__ */

#endif /* HAL_ARCH_EXCEPTION_H */
