#ifndef HAL_ARCH_EXCEPTION_H
#define HAL_ARCH_EXCEPTION_H

#ifndef __ASSEMBLER__
#include <stdint.h>
#include <plane/compiler.h>

struct interrupt_frame {
    /* generated by pusha macro */
    uint64_t r15;
    uint64_t r14;
    uint64_t r13;
    uint64_t r12;
    uint64_t r11;
    uint64_t r10;
    uint64_t r9;
    uint64_t r8;
    uint64_t rbp;
    uint64_t rdi;
    uint64_t rsi;
    uint64_t rdx;
    uint64_t rcx;
    uint64_t rbx;
    uint64_t rax;

    /* interrupt route info */
    uint64_t int_no;       /* 0~255 */
    uint64_t error_code;   /* manually push 0 if hardware does not handle error code */

    /* handled by hardware */
    uint64_t rip;          /* address of interrupted instruction */
    uint64_t cs;           /* interrupted cs */
    uint64_t rflags;       /* interrupted rflags */
    uint64_t rsp;          /* interrupted rsp, available only when privilege level changes */
    uint64_t ss;           /* interrupted ss, available only when privilege level changes */
} __attribute__((packed));

void x86_64_exception_handler(struct interrupt_frame *frame);

#endif /* __ASSEMBLER__ */

#endif /* HAL_ARCH_EXCEPTION_H */